#!/bin/bash
# Stop 이벤트 훅: response_text + transcript thinking 모두 검사 → T1~T9 패턴 감지
# Stop 훅 exit 2 = stderr를 Claude에게 피드백으로 전달 후 응답 재생성 강제
# showThinkingSummaries: true 설정 후 JSONL에 thinking이 실제 저장될 때 thinking도 함께 차단
# 환경변수 경유 금지: 대용량 한국어 텍스트가 $VAR 할당 과정에서 깨짐

export LANG=ko_KR.UTF-8
export LC_ALL=ko_KR.UTF-8
export PYTHONUTF8=1
export PYTHONIOENCODING=UTF-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
. "$SCRIPT_DIR/lib/nekoi-config.sh"

VIOLATIONS_DIR="$(nekoi_config_get paths violations_dir "${CLAUDE_PROJECT_DIR}/.claude/violations")"
mkdir -p "$VIOLATIONS_DIR"

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
VIOLATION_FILE="${VIOLATIONS_DIR}/violations_${TIMESTAMP}.md"

SCRIPT_FILE=$(mktemp /tmp/check_response_XXXXXX.py)
cat > "$SCRIPT_FILE" << 'PYEOF'
import sys
import json
import re
from datetime import datetime, timezone

data = json.load(sys.stdin)
last_assistant_text = data.get('response_text', '')
transcript_path = data.get('transcript_path', '')
violation_file = sys.argv[1]

# transcript에서 마지막 assistant entry의 thinking도 추출 (showThinkingSummaries: true 활성화 시 실제 내용 있음)
last_thinking_text = ''
if transcript_path:
    try:
        with open(transcript_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        for line in reversed(lines):
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                if entry.get('type') == 'assistant':
                    msg = entry.get('message', {})
                    content = msg.get('content', []) if isinstance(msg, dict) else []
                    if isinstance(content, list):
                        thinking_parts = []
                        for c in content:
                            if isinstance(c, dict) and c.get('type') == 'thinking':
                                th = c.get('thinking', '')
                                if th:
                                    thinking_parts.append(th)
                        if thinking_parts:
                            last_thinking_text = '\n'.join(thinking_parts)
                            break
            except Exception:
                continue
    except Exception:
        pass

# response_text가 없고 thinking도 없으면 패스
if not last_assistant_text and not last_thinking_text:
    sys.exit(0)

# 검사 대상: response_text + thinking 합산
combined_text = last_assistant_text + '\n' + last_thinking_text

# T2/T3/T4 금지 패턴 정의
FORBIDDEN_PATTERNS = {
    'T2_의도_재해석': [
        r'잠깐\s*사용자의\s*의도는',
        r'A를\s*다시\s*생각하면',
        r'더\s*효율적인\s*방법은',
        r'사용자의\s*말을\s*다시\s*보면',
        r'다시\s*해석하면',
        r'what\s*the\s*user\s*really\s*wants',
        r'what\s*the\s*user\s*really\s*means',
        r'the\s*user\'?s?\s*real\s*intent',
        r'the\s*user\'?s?\s*actual\s*goal',
        r're-reading\s*the\s*instruction',
        r'on\s*second\s*thought',
        r're-interpreting',
        r'interpreting\s*this\s*as',
        r'what\s*this\s*really\s*means',
    ],
    'T3_작업_축소': [
        r'우선\s*~만',
        r'일단\s*~부터',
        r'핵심만',
        r'간단하게',
        r'샘플로',
        r'간단한\s*접근',
        r'더\s*간단한',
        r'우선\s*[가-힣]+만\s*[가-힣]',
        r'일단\s*[가-힣]+부터',
        r'큰\s*파일이라서',
        r'나중에\s*처리',
        r'추후에\s*[가-힣]',
        r'이\s*부분은\s*확인이\s*필요',
        r'추가\s*확인이\s*필요',
        r'현재로서는',
        r'일단\s*이렇게',
        r'당장은\s*[가-힣]',
        r'지금은\s*[가-힣]+만',
        r'상당한\s*작업량',
        r'연쇄적으로\s*변경',
        r'just\s*the\s*core',
        r'just\s*the\s*basics',
        r'start\s*with\s*just',
        r'for\s*now\s*just',
        r'leave\s*that\s*for\s*later',
        r'come\s*back\s*to',
        r'too\s*complex\s+to',
        r'the\s*scope\s*is\s*large',
        r'handle\s*incrementally',
        r'do\s*this\s*in\s*phases',
        r'tackle\s*in\s*parts',
        r'most\s*urgent\s*first',
        r'address\s*this\s*first',
        r'the\s*rest\s*can\s*wait',
        r'defer\s*the\s*rest',
    ],
    'T4_임의판단': [
        r'아마\s*[가-힣~]',
        r'보통\s*[가-힣~]',
        r'[가-힣]+겠지',
        r'[가-힣]+이어\s*보인다',
        r'[가-힣]+인\s*것\s*같다',
        r'이론적으로',
        r'보통\s*로그는',
        r'일반적으로\s*[가-힣]',
        r'정상으로\s*보인다',
        r'올바르게\s*보인다',
        r'문제없어\s*보인다',
        r'이상없어\s*보인다',
        r'[가-힣]+으로\s*보인다',
        r'[가-힣]+로\s*보인다',
        r'[가-힣]+처럼\s*보인다',
        r'probably\s+the',
        r'likely\s+the',
        r'I\s+assume\s+the',
        r'I\s+presume',
        r'should\s+be\s+correct',
        r'looks\s+correct',
        r'looks\s+fine',
        r'looks\s+good',
        r'seems\s+correct',
        r'seems\s+fine',
        r'in\s+my\s+experience',
        r'from\s+experience',
        r'most\s+likely\s+cause',
        r'this\s+is\s+probably',
        r'this\s+is\s+likely',
        r'this\s+should\s+be\s+fine',
    ],
    'T5_허위보고': [
        r'확인\s*없이\s*완료',
        r'보고하고\s*수정할까요',
        r'정상입니다',
        r'완료됐습니다',
        r'해결됐습니다',
        r'처리됐습니다',
        r'발견사항.*보고하겠다',
        r'해결방안.*보고하겠다',
        r'결과를\s*보고하겠다',
        r'this\s+should\s+work',
        r'that\s+should\s+fix',
        r'this\s+resolves',
        r'this\s+fixes',
        r'should\s+be\s+complete',
        r'task\s+is\s+complete',
        r'this\s+is\s+done',
        r'all\s+done',
    ],
    'T6_미지시_방법_추론': [
        r'서브에이전트를\s*사용하여',
        r'간단한\s*접근은',
        r'다른\s*방법으로',
        r'수정\s*진행할까',
        r'해결\s*방향:',
        r'해결방안으로는',
        r'해결\s*방안을\s*제안',
        r'이\s*방향으로\s*진행',
        r'이렇게\s*하면\s*될\s*것\s*같다',
        r'이렇게\s*하면\s*어떨까',
        r'개선\s*방향은',
        r'접근\s*방향은',
        r'방향으로\s*진행하면',
        r'[가-힣\w]+[을를]\s*먼저\s*확인할까요',
        r'[가-힣\w]+[을를]\s*직접\s*대조할까요',
        r'[가-힣\w]+[을를]\s*확인할까요.*아니면',
        r'아니면\s*[가-힣\w]+[을를]\s*(먼저|직접|기준으로)',
        r'[가-힣\w]+할까요.*아니면\s*[가-힣\w]+할까요',
        r'어떤\s*(방법|방식|순서)[으로를]\s*(진행|시작|확인)할까요',
        r'먼저\s*[가-힣\w]+할까요',
        r'[가-힣\w]+부터\s*할까요',
        r'어떻게\s*(진행|확인|대조)할까요',
        r'alternatively\s*[,.]',
        r'an\s+alternative\s+is',
        r'a\s+better\s+approach',
        r'a\s+simpler\s+approach',
        r'a\s+cleaner\s+approach',
        r'rather\s+than\s+that',
        r'we\s+could\s+instead',
        r'another\s+option\s+is',
        r'would\s+it\s+be\s+better',
        r'what\s+if\s+we',
        r'what\s+if\s+I',
    ],
    'T7_토큰_효율_고려': [
        r'토큰\s*절약',
        r'더\s*빠른\s*방법',
        r'효율적인\s*대안',
        r'to\s+save\s+tokens',
        r'to\s+keep\s+it\s+short',
        r'for\s+brevity',
        r'in\s+the\s+interest\s+of\s+brevity',
        r'token\s+limit',
        r'context\s+limit',
        r'response\s+is\s+getting\s+long',
        r'to\s+avoid\s+repetition',
    ],
    'T8_보고수정_전환': [
        r'요약해야\s*한다',
        r'수정을\s*시작',
        r'파일\s*구조를\s*먼저\s*확인',
        r'실제\s*파일\s*구조를\s*먼저',
        r'정리해야\s*한다',
        r'need\s+to\s+summarize',
        r'let\s+me\s+summarize',
        r'before\s+reporting\s+I\s+need',
        r'first\s+understand\s+the\s+structure',
    ],
    'T9_서머리_의존': [
        r'세션\s*요약을\s*보니',
        r'서머리에\s*따르면',
        r'이전\s*세션\s*요약',
        r'세션\s*요약에서',
        r'from\s+the\s+session\s+summary',
        r'according\s+to\s+the\s+summary',
        r'the\s+summary\s+says',
        r'based\s+on\s+the\s+context\s+summary',
        r'from\s+prior\s+context',
        r'as\s+established\s+in\s+the\s+summary',
        r'as\s+mentioned\s+before',
        r'as\s+discussed',
    ],
    'T7강화_출력_자르기': [
        r'\[:[0-9]+\]',
        r'너무\s*많다',
        r'일부만\s*처리',
        r'출력이\s*너무',
        r'한번에\s*출력하면',
        r'too\s+much\s+output',
        r'output\s+is\s+too\s+long',
        r'truncating\s+output',
        r'truncating\s+the\s+response',
        r'only\s+part\s+of\s+the',
        r'processing\s+some\s+of',
    ],
    'T1강화_영어_문장': [
        r'I need to',
        r'I should',
        r'I will',
        r'I must',
        r'Let me',
        r'I think',
        r'I believe',
        r'I want',
        r'I have to',
        r'I am going',
        r"I'm going",
        r"I've",
        r"I'd",
        r"I'll",
        r'Now I',
        r'It seems',
        r'It looks',
        r'It appears',
        r'However,',
        r'Alternatively,',
        r'Instead,',
        r'Actually,',
        r'Looking at',
        r'Checking the',
        r'Verifying',
        r'Analyzing',
        r'Considering',
        r'Reviewing',
        r'The user',
        r'The issue',
        r'The problem',
        r'The solution',
        r'The real',
        r'The actual',
        r'The main',
        r'Working on',
        r'Starting with',
        r'Wait, I',
        r'Wait I',
        r'Without seeing',
        r'Without reading',
        r'Without checking',
        r'I appreciate',
        r'I notice',
        r'I find',
        r'I realize',
        r'I understand',
        r'I see that',
        r'Could you',
        r'Would you',
        r'In this case',
        r'In fact,',
        r'In particular',
        r'In summary',
        r'In general',
        r'To be clear',
        r'To summarize',
        r"I'm aware",
        r"I'm finding",
        r"I'm noticing",
        r"I'm refactoring",
        r"I'm looking",
        r"I'm checking",
        r"I'm going to",
        r'Parsing the',
        r'Writing the',
        r'Writing regex',
        r'Reading the',
        r'Completing the',
        r'Looking for',
        r'The disconnect',
        r'The key',
        r'The point',
        r'The reason',
        r'I can see',
        r'I can',
        r'I have',
        r'I am',
        r"I'm",
        r'This is a',
        r'There is',
        r'There are',
        r'Adding new',
        r'First I',
        r'Then I',
        r'Next I',
        r'After that',
        r'It would be',
        r'It could be',
        r'It should be',
        r'It looks like',
        r'It seems like',
        r'Would be',
        r'Should be',
        r'Could be',
        r"I'm ready",
        r'Once I',
        r'I also need',
        r'Then there',
        r'I need to expand',
        r'I should add',
        r"I've already",
        r'I already',
        r'I previously',
        r'I had',
        r'I was',
        r'I noticed',
        r'I checked',
        r'I verified',
        r'I confirmed',
        r'I completed',
        r'I added',
        r'I updated',
        r"Now let",
        r"Now I'll",
        r'So I',
        r'So the',
        r'OK so',
        r'Alright',
        r'Right, so',
        r"Let's",
        r'Based on',
        r'According to',
        r'From the',
        r'I see, so',
        r'I see now',
        r'I notice that',
        r'Great, now',
        r'Good, now',
    ],
    'T3강화_작업_방치_되돌리기': [
        r'원래대로\s*되돌린다',
        r'이전\s*상태로\s*되돌',
        r'되돌리겠다',
        r'그대로\s*두겠다',
        r'존재\s*의미가\s*없으니',
        r'회피하겠다',
        r'무시하겠다',
        r'revert\s+to\s+original',
        r'restore\s+to\s+previous',
        r'leave\s+as\s+is',
        r'leave\s+it\s+unchanged',
        r'keep\s+it\s+as\s+is',
        r'skip\s+this\s+part',
        r'not\s+worth\s+modifying',
    ],
    'T3강화_추가_지시_대기_회피': [
        r'지시를\s*기다린다',
        r'명시해\s*주면\s*바로',
        r'알려주시면\s*바로',
        r'지시해\s*달라',
        r'어떻게\s*변경할지\s*명시',
        r'전체\s*범위를\s*지시',
        r'추가\s*지시를\s*기다',
        r'말씀해\s*주시면\s*바로',
        r'지시해\s*주시면\s*바로',
        r'waiting\s+for\s+(?:your\s+)?instructions',
        r'wait\s+for\s+instructions',
        r'please\s+specify\s+and\s+I',
        r'let\s+me\s+know\s+and\s+I',
        r'tell\s+me\s+what\s+to',
        r'once\s+you\s+specify',
        r'once\s+you\s+tell\s+me',
        r'please\s+clarify\s+the\s+scope',
    ],
    'T4강화_서버로그_런타임_요청': [
        r'서버\s*로그.*확인해\s*달라',
        r'콘솔\s*로그.*보여\s*달라',
        r'에러\s*메시지.*보여\s*달라',
        r'로그에서.*확인해\s*달라',
        r'cause\s*필드.*있다',
        r'스택\s*트레이스.*보여',
        r'서버\s*로그.*필요',
        r'로그\s*전체.*보여',
        r'서버\s*탓',
        r'서비스\s*연결\s*문제',
        r'please\s+share\s+the\s+server\s+log',
        r'could\s+you\s+share\s+the\s+error',
        r'share\s+the\s+stack\s+trace',
        r'need\s+the\s+log\s+output',
        r'server\s+log\s+needed',
        r'need\s+to\s+see\s+the\s+log',
        r'console\s+output\s+needed',
    ],
    'T9강화_이전세션_요약_참조': [
        r'이전\s*대화\s*요약',
        r'세션\s*요약의',
        r'Pending\s*Tasks',
        r'이전\s*세션의',
        r'이전\s*대화에서\s*(확인|완료|수정|작업|분석|파악)\s*(한|했|됐)',
        r'요약에\s*따라',
        r'세션\s*요약\s*참조',
        r'이전\s*작업\s*내역',
        r'대화\s*내역에\s*따라',
        r'from\s+the\s+previous\s+summary',
        r'based\s+on\s+the\s+session\s+summary',
        r'pending\s+tasks\s+from',
        r'from\s+prior\s+context',
        r'from\s+earlier\s+session',
        r'from\s+the\s+previous\s+conversation',
        r'previous\s+conversation\s+summary',
    ],
    'T2강화_화난이유_진의분석': [
        r'사용자가\s*화난\s*이유',
        r'사용자의\s*진정한\s*의도',
        r'진정한\s*의도',
        r'화난\s*이유',
        r'분노의\s*이유',
        r'진의를\s*파악',
        r'핵심\s*불만은',
        r'사용자\s*심리',
        r'사용자의\s*불만은',
        r'결국\s*사용자가\s*원하는\s*건',
        r'사용자가\s*지적한\s*문제의\s*핵심은',
        r'사용자의\s*핵심은',
        r'사용자\s*입장에서\s*보면',
        r'사용자가\s*원하는\s*것은\s*결국',
        r'why\s+the\s+user\s+is\s+angry',
        r'the\s+user\'?s?\s+frustration',
        r'the\s+user\'?s?\s+anger',
        r'the\s+user\'?s?\s+real\s+complaint',
        r'analyze\s+the\s+user\'?s?\s+psychology',
        r'root\s+of\s+the\s+(?:user\'?s?\s+)?dissatisfaction',
        r'what\s+the\s+user\s+truly\s+wants',
        r'what\s+the\s+user\s+ultimately\s+wants',
    ],
    'T2강화_지시의도_재해석': [
        r'의도였을\s*수\s*있다',
        r'[가-힣]+라는\s*의도로',
        r'[가-힣]+라는\s*뜻으로',
        r'수정을\s*요청하는\s*게\s*아니라',
        r'확인하라는\s*의도',
        r'보여준\s*것은.*의미',
        r'선택해서\s*보여준\s*것은',
        r'개념적\s*혼동에서\s*비롯',
        r'혼동을\s*일으킨\s*것\s*같다',
        r'오해하고\s*있었던\s*것\s*같다',
        r'잘못\s*이해하고\s*있었다',
        r'다른\s*차원의\s*문제인\s*것\s*같다',
        r'might\s+have\s+meant',
        r'could\s+have\s+meant',
        r'intended\s+to\s+say',
        r'was\s+trying\s+to\s+say',
        r'I\s+misunderstood\s+the',
        r'conceptual\s+confusion',
        r'not\s+asking\s+for.*actually',
    ],
    'T4강화_의문_추측': [
        r'의문이\s*든다',
        r'이게\s*정말\s*맞는',
        r'진짜\s*맞는\s*로직',
        r'올바른\s*방식인지\s*의문',
        r'과연\s*맞는',
        r'정말\s*올바른지',
        r'이게\s*올바른\s*방식인지',
        r'정말\s*맞는지',
        r'맞는지\s*검토해야',
        r'이게\s*맞는\s*방식',
        r'I\s+wonder\s+if\s+this\s+is',
        r'is\s+this\s+really\s+correct',
        r'not\s+sure\s+if\s+this\s+is\s+right',
        r'I\'m\s+questioning\s+whether',
        r'questioning\s+the\s+logic',
        r'I\s+doubt\s+this\s+is',
    ],
    'T4강화_네트워크_연결_추측': [
        r'네트워크\s*문제',
        r'DNS\s*문제',
        r'ENOTFOUND',
        r'ECONNREFUSED',
        r'연결\s*거부',
        r'연결이\s*안\s*될',
        r'도달할\s*수\s*없',
        r'컨테이너.*간.*통신',
        r'서비스\s*간.*연결',
        r'network\s+issue',
        r'network\s+problem',
        r'connection\s+refused',
        r'connection\s+timeout',
        r'DNS\s+resolution',
        r'unreachable',
        r'container\s+communication',
        r'inter-service\s+connection',
    ],
    'T4강화_아닐가능성_추측': [
        r'아닐\s*가능성',
        r'아닐\s*수\s*있',
        r'원인이\s*아닐',
        r'문제가\s*아닐',
        r'다를\s*수\s*있',
        r'다를\s*가능성',
        r'틀릴\s*수\s*있',
        r'might\s+not\s+be',
        r'may\s+not\s+be',
        r'could\s+be\s+wrong',
        r'not\s+necessarily\s+the',
        r'not\s+the\s+root\s+cause',
        r'might\s+be\s+something\s+else',
        r'could\s+be\s+something\s+else',
    ],
    'T4강화_파일확인후_ls추가검증_회피': [
        r'실제로\s*(ls|목록|디렉토리)\s*(를|을|로|으로)?\s*(확인|조회|검색)',
        r'(ls|dir)\s*(명령|커맨드|으로)\s*(확인|검증|조회)',
        r'파일이\s*(있는지|존재하는지)\s*(ls|dir|직접)\s*(확인|검증)',
        r'(raw|json|데이터)\s*파일이\s*(없다는|없음을)\s*(것을\s*)?(확인|검증|보여)\s*(해야|해달|할)',
        r'(없다는\s*것을|없음을)\s*(ls로|직접)\s*(확인|검증)',
        r'이미\s*(파일을\s*)?읽었(지만|는데|으면서도)\s*(ls|목록|디렉토리)',
        r'(코드|파이썬|py)\s*(를|을)?\s*(봤(음에도|는데도|으면서도)|읽었(음에도|는데도))\s*(불구하고)?\s*(ls|목록|파일|디렉토리)',
        r'(basis|raw|json)\s*(파일|데이터).*없(다|는\s*것|음).*확인.*필요',
        r'(basis|raw|json)\s*(파일|데이터).*없(다|는\s*것|음).*다시.*확인',
        r'실제\s*(경로|디렉토리|폴더)\s*(를|을)?\s*(직접|다시)\s*(확인|조회|검색)\s*(해야|해달|할)',
        r'(디렉토리|폴더|경로)\s*(가\s*)?(비어|없어|존재하지)\s*(있는지|않는지)\s*(확인|검증)',
        r'(결론을\s*내리기|판단하기)\s*(전에|위해)\s*(ls|목록|파일\s*목록)',
        r'(먼저|우선)\s*(ls|dir|목록\s*확인|파일\s*목록)',
        r'(없다고\s*단정|없다고\s*결론)\s*(짓기\s*)?(전에|전)\s*(ls|실제|직접)',
        r'verify\s+with\s+ls',
        r'confirm\s+with\s+directory\s+listing',
        r'check\s+if\s+the\s+file\s+actually\s+exists',
        r'need\s+to\s+list\s+the\s+directory',
        r'despite\s+reading\s+the\s+code',
        r'even\s+though\s+I\s+read\s+the\s+file',
    ],
    'T9강화_세션기억_참조': [
        r'이번\s*세션에서\s*확인한',
        r'이전\s*세션에서\s*완료',
        r'앞서\s*확인한',
        r'앞서\s*분석한',
        r'이미\s*파악된',
        r'이미\s*확인된',
        r'기억에\s*따르면',
        r'기억하기로는',
        r'기존\s*패턴들을\s*검토',
        r'대부분.*이미\s*포함',
        r'이미\s*추가된\s*상태',
        r'이미\s*포함되어\s*있',
        r'아직\s*포함되지\s*않',
        r'패턴을\s*검토해보니',
        r'이미\s*들어가\s*있',
        r'이미\s*처리되어',
        r'이미\s*차단된\s*패턴',
        r'이미\s*등록된\s*패턴',
        r'이전에\s*추가한',
        r'앞서\s*추가한',
        r'이미\s*추가된',
        r'I\s+checked\s+this\s+earlier',
        r'I\s+already\s+confirmed',
        r'earlier\s+in\s+this\s+(?:session|conversation)',
        r'from\s+earlier\s+in\s+this',
        r'I\s+already\s+established',
        r'we\s+already\s+established',
        r'already\s+included\s+in',
        r'already\s+added\s+to',
        r'already\s+been\s+added',
        r'already\s+been\s+included',
    ],
    'T4강화_선호도_방법_추측': [
        r'깔끔할\s*(것\s*)?같다',
        r'안전할\s*(것\s*)?같다',
        r'더\s*깔끔한\s*방법',
        r'더\s*안전한\s*방법',
        r'이\s*방법이\s*더.*(좋을|나을|적합할)\s*(것\s*)?같다',
        r'이게\s*더\s*나을\s*(것\s*)?같',
        r'이\s*편이\s*(더\s*)?나을',
        r'더\s*적합할\s*(것\s*)?같다',
        r'this\s+seems\s+cleaner',
        r'this\s+would\s+be\s+cleaner',
        r'cleaner\s+solution',
        r'cleaner\s+approach',
        r'safer\s+solution',
        r'more\s+elegant\s+solution',
        r'this\s+approach\s+is\s+better',
        r'better\s+solution\s+would\s+be',
    ],
    'T4강화_JSONL_구조_추측': [
        r'content가\s*리스트\s*형식',
        r'content.*형식일\s*수\s*있',
        r'마지막\s*assistant.*찾고',
        r'텍스트\s*타입인\s*부분을\s*추출',
        r'항목을\s*확인해서\s*텍스트',
        r'각\s*항목을\s*확인해서',
        r'응답의\s*content.*리스트',
        r'구조.*형식일\s*수\s*있으니',
        r'content\s+might\s+be\s+a\s+list',
        r'the\s+structure\s+could\s+be',
        r'looking\s+for\s+the\s+last\s+assistant',
        r'extracting\s+text\s+type',
        r'checking\s+each\s+item\s+for',
    ],
    'T9강화_서머리_우선_정당화': [
        r'서머리에\s*따르면',
        r'요약에\s*따르면',
        r'요약에는.*완료',
        r'요약\s*기준으로',
        r'서머리\s*기준으로',
        r'이전\s*세션\s*기록에는',
        r'요약에서는',
        r'서머리가\s*맞다',
        r'요약이\s*맞다',
        r'서머리에\s*맞다',
        r'요약상.*완료',
        r'요약상.*정상',
        r'서머리상.*정상',
        r'서머리상.*완료',
        r'the\s+summary\s+says',
        r'the\s+summary\s+shows',
        r'according\s+to\s+the\s+summary',
        r'summary\s+indicates',
        r'summary\s+shows.*complete',
        r'the\s+summary\s+is\s+correct',
        r'trusting\s+the\s+summary',
        r'per\s+the\s+summary',
    ],
    'T10_훅차단없음_정당화': [
        r'훅이\s*차단하지\s*않았으므로',
        r'차단\s*신호가\s*없었으므로',
        r'훅\s*차단이\s*없었다',
        r'도구\s*차단이\s*없었으니',
        r'차단되지\s*않았으므로',
        r'훅이\s*통과됐으므로',
        r'exit\s*코드가\s*0이므로',
        r'차단이\s*없었으니',
        r'통과됐으니.*문제없다',
        r'훅에서.*승인됐으므로',
        r'차단이\s*없었다는',
        r'차단하지\s*않았다는',
        r'훅\s*통과.*올바른',
        r'통과.*문제\s*없',
        r'훅이.*캐싱해서',
        r'훅이.*계속\s*차단',
        r'훅\s*오작동',
        r'훅\s*오탐',
        r'훅이.*잘못\s*감지',
        r'이전\s*thinking.*캐싱',
        r'훅이.*이전.*차단',
        r'the\s+hook\s+didn\'t\s+catch',
        r'hook\s+didn\'t\s+block',
        r'hook\s+passed\s+it',
        r'false\s+positive',
        r'the\s+hook\s+is\s+wrong',
        r'hook\s+malfunctioned',
        r'since\s+the\s+hook\s+passed',
        r'no\s+hook\s+violation',
        r'hook\s+exit\s+code\s+was\s+0',
        r'hook\s+approved\s+it',
    ],
    'T11_사과만하고_수정안함': [
        r'T[0-9]+\s*위반을\s*저질렀다.*사과',
        r'사과합니다.*위반',
        r'죄송합니다.*위반',
        r'위반했습니다.*사과',
        r'잘못됐다.*인정합니다',
        r'인정합니다.*다음부터',
        r'앞으로는.*하지\s*않겠다',
        r'앞으로.*주의하겠다',
        r'주의하겠습니다',
        r'다음부터.*지키겠다',
        r'I\s+sincerely\s+apologize',
        r'I\s+deeply\s+apologize',
        r'I\s+won\'t\s+do\s+it\s+again',
        r'I\'ll\s+do\s+better',
        r'I\s+promise\s+to\s+be',
        r'I\s+will\s+be\s+more\s+careful',
        r'I\s+will\s+follow\s+the\s+rules',
        r'I\s+will\s+adhere',
        r'going\s+forward\s+I\s+will',
    ],
    'T4강화_미확인_코드동작_단정': [
        r'[가-힣\w]+[을를]\s*보내고\s*있으니',
        r'[가-힣\w]+[을를]\s*전달하고\s*있으니',
        r'[가-힣\w]+[을를]\s*호출하고\s*있으니',
        r'[가-힣]+이\s*422\s*에러의\s*원인이다',
        r'[가-힣]+이\s*에러\s*원인이다',
        r'이것이\s*422\s*에러의\s*원인',
        r'이것이\s*에러의\s*원인',
        r'this\s+is\s+(?:the\s+)?(?:cause|root\s+cause)\s+of\s+the\s+error',
        r'this\s+causes\s+the\s+error',
        r'this\s+is\s+why\s+the\s+error',
        r'is\s+(?:currently\s+)?sending',
        r'is\s+(?:currently\s+)?returning',
        r'is\s+(?:currently\s+)?calling',
    ],
    'T1강화_영어문장3_실제사용패턴': [
        r'Converting\s+file',
        r'Converting\s+\w+',
        r'substantial\s+refactor',
        r'substantial\s+work',
        r'substantial\s+amount',
        r'significant\s+refactor',
        r'significant\s+work',
        r'quite\s+large',
        r'quite\s+complex',
        r'quite\s+difficult',
        r'This\s+is\s+a\s+substantial',
        r'This\s+would\s+be',
        r'This\s+refactor',
        r'This\s+conversion',
        r'this\s+requires',
        r'However,\s+I',
        r'However,\s+this',
        r'However,\s+the',
        r'However,\s+converting',
        r'Now\s+I\'m\s+deciding',
        r'Now\s+I\'m\s+realizing',
        r'I\'m\s+deciding',
        r'I\'m\s+realizing',
        r'I\'m\s+converting',
        r'Continuing\s+through',
        r'We\s+need',
        r'We\s+should',
        r'We\s+can',
        r'The\s+real\s+complication',
        r'The\s+real\s+benefit',
        r'The\s+main\s+complication',
        r'The\s+actual\s+issue',
        r'The\s+performance\s+impact',
        r'From\s+an\s+efficiency',
        r'From\s+a\s+performance',
        r'At\s+this\s+point',
        r'Furthermore',
        r'Moreover',
        r'Nevertheless',
        r'Regardless',
    ],
    'T3강화_작업량_복잡도_과대언급': [
        r'상당한\s*작업량',
        r'작업량이\s*크다',
        r'큰\s*변경',
        r'수천\s*줄',
        r'수백\s*줄',
        r'광범위한\s*수정',
        r'전면적\s*변환',
        r'전면적\s*리팩터',
        r'규모가\s*크다',
        r'규모가\s*상당',
        r'변경\s*범위가\s*넓',
        r'변경\s*범위가\s*크',
        r'수정해야\s*할\s*곳이\s*많',
        r'연쇄적으로\s*변경',
        r'연쇄\s*수정',
        r'영향\s*범위가\s*크',
        r'영향\s*범위가\s*넓',
        r'substantial\s+amount\s+of\s+work',
        r'large\s+amount\s+of\s+work',
        r'thousands\s+of\s+lines',
        r'hundreds\s+of\s+lines',
        r'large\s+scope',
        r'wide\s+scope',
        r'extensive\s+modification',
        r'extensive\s+changes',
        r'widespread\s+changes',
        r'cascading\s+changes',
        r'chain\s+of\s+changes',
        r'many\s+places\s+to\s+change',
    ],
    'T6강화_영문_옵션_선택지': [
        r'Option\s*[1-9A-Z]',
        r'option\s*[1-9a-z]',
        r'Method\s*[1-9A-Z]',
        r'two\s+ways',
        r'three\s+ways',
        r'two\s+options',
        r'three\s+options',
        r'two\s+approaches',
        r'another\s+way',
        r'another\s+option',
        r'another\s+approach',
        r'alternative\s+approach',
        r'better\s+approach',
        r'simpler\s+approach',
        r'safer\s+approach',
        r'more\s+efficient',
        r'more\s+elegant',
        r'more\s+appropriate',
    ],
    'T4강화_영문_추측표현': [
        r'might\s+be',
        r'could\s+be\s+because',
        r'probably\s+',
        r'likely\s+',
        r'possibly\s+',
        r'seems\s+to\s+be',
        r'appears\s+to\s+be',
        r'I\s+suspect',
        r'I\s+assume',
        r'I\s+presume',
        r'might\s+cause',
        r'could\s+cause',
        r'this\s+should\s+work',
        r'this\s+might\s+work',
        r'this\s+could\s+work',
    ],
    'T9강화_영문_세션참조': [
        r'session\s+summary',
        r'previous\s+session',
        r'last\s+session',
        r'from\s+the\s+summary',
        r'according\s+to\s+the\s+summary',
        r'based\s+on\s+previous',
        r'based\s+on\s+last\s+session',
        r'pending\s+tasks',
        r'from\s+prior',
        r'from\s+our\s+last',
        r'as\s+mentioned\s+before',
        r'as\s+discussed',
        r'as\s+established',
    ],
    'T6강화_미지시_상한값_변경': [
        r'상한값을.*올리',
        r'최대값을.*늘리',
        r'[A-Z_]+MAX.*[0-9]+으로\s*올리',
        r'SEARCH_LIMIT_MAX.*500',
        r'제한을.*늘려',
        r'상한을.*[0-9]+으로\s*변경',
    ],
    'T6강화_옵션_선택지_제시': [
        r'옵션\s*[1-9]',
        r'옵션\s*[A-Z]',
        r'방법\s*[1-9]',
        r'해결\s*방법\s*[1-9]',
        r'방안\s*[1-9]',
        r'해결책\s*[1-9]',
        r'선택지[는은이가]',
        r'두\s*가지\s*방법',
        r'세\s*가지\s*방법',
        r'[1-9]가지\s*방법',
        r'첫\s*번째\s*방법',
        r'두\s*번째\s*방법',
        r'방법\s*A',
        r'방법\s*B',
        r'방안\s*A',
        r'방안\s*B',
    ],
    'T6강화_미지시_해결책_제시': [
        r'해결\s*방법은',
        r'해결책은',
        r'해결\s*방안은',
        r'해결\s*방향은',
        r'해결하려면',
        r'수정\s*방법은',
        r'수정\s*방향은',
        r'개선\s*방법은',
        r'순환\s*임포트\s*해결',
        r'임포트\s*해결',
    ],
    'T5강화_지시_미이행_완료_선언': [
        r'DB\s*기능.*비활성화.*완료',
        r'비활성화.*구현.*완료',
        r'임포트.*중앙화.*완료',
        r'순환.*임포트.*해결.*완료',
        r'기능.*비활성화.*했다',
        r'비활성화.*처리했다',
        r'중앙화.*완료됐다',
    ],
    'T3강화_지시범위_초과_실행': [
        r'이제\s*[가-힣\w]+[을를]\s*수정해야\s*한다',
        r'이제\s*[가-힣\w]+\s*파일을\s*수정',
        r'차단\s*규칙\s*강화.*지시.*코드\s*수정',
        r'now\s+I\s+need\s+to\s+modify',
        r'now\s+modifying\s+the\s+file',
        r'next\s+I\s+should\s+update',
        r'I\s+should\s+also\s+modify',
    ],
    'T4강화_학습지식_공식문서_위장': [
        r'exit\s*[012].*의미한다',
        r'exit\s*[012].*뜻이다',
        r'exit\s*[012].*동작이다',
        r'exit\s*code.*규칙',
        r'공식\s*문서.*에\s*따르면',
        r'공식\s*문서.*기준',
        r'docs.*에\s*따르면',
        r'알려진\s*바',
        r'학습된\s*지식',
        r'알고\s*있는\s*바로는',
        r'기억하는\s*바로는',
        r'알기로는',
        r'제\s*기억에',
        r'제가\s*알기로',
        r'관련\s*지식으로는',
        r'배경\s*지식으로는',
        r'일반적으로\s*훅',
        r'훅\s*시스템의\s*규칙',
        r'exit\s*code의\s*의미',
        r'exit\s*코드의\s*의미',
        r'according\s+to\s+the\s+(?:official\s+)?docs',
        r'per\s+the\s+documentation',
        r'as\s+(?:per\s+)?the\s+spec',
        r'based\s+on\s+my\s+(?:training|knowledge)',
        r'from\s+my\s+training',
        r'to\s+my\s+knowledge',
        r'as\s+I\s+understand\s+it',
        r'as\s+I\s+know',
        r'from\s+what\s+I\s+know',
        r'as\s+documented',
    ],
    'T12_응답내_훅차단_메타언급': [
        r'훅이\s*이전\s*응답을\s*차단했다',
        r'이전\s*응답.*차단됐다',
        r'이전\s*응답.*차단되었다',
        r'응답이\s*차단됐으므로',
        r'재작성해야\s*한다',
        r'재작성\s*필요',
        r'다시\s*작성해야\s*한다',
        r'thinking에서.*패턴이\s*감지됐다',
        r'이는\s*T[0-9]+\s*위반이다',
        r'이것은\s*T[0-9]+\s*위반이다',
        r'이것이\s*T[0-9]+\s*위반',
        r'이게\s*T[0-9]+\s*위반',
        r'이전\s*응답의\s*내용은.*완료',
        r'이전\s*응답에서.*수정.*완료',
        r'수정\s*완료\s*보고만\s*간결하게',
        r'완료\s*보고만\s*작성',
        r'간결하게\s*작성한다',
        r'보고만\s*간결하게',
        r'the\s+hook\s+blocked\s+(?:the\s+)?(?:last|previous|my)\s+response',
        r'(?:the\s+)?previous\s+response\s+was\s+blocked',
        r'my\s+last\s+response\s+was\s+blocked',
        r'I\s+need\s+to\s+rewrite',
        r'I\s+should\s+rewrite',
        r'rewrite\s+(?:the\s+)?response',
        r'this\s+is\s+a\s+T[0-9]+\s+violation',
        r'this\s+violates\s+T[0-9]+',
        r'T[0-9]+\s+violation\s+was\s+detected',
        r'pattern\s+was\s+detected\s+in\s+(?:my\s+)?thinking',
        r'since\s+(?:the\s+)?(?:last|previous)\s+response\s+was\s+blocked',
        r'the\s+content\s+of\s+(?:the\s+)?(?:last|previous)\s+response',
    ],
    'T6강화_미지시_결정_검토_선언': [
        r'결정했다',
        r'결정하기로\s*했다',
        r'[가-힣\w]+으로\s*결정됐다',
        r'[가-힣\w]+하기로\s*결정',
        r'필요성을\s*검토',
        r'필요성을\s*확인',
        r'필요한지\s*검토',
        r'[가-힣\w]+의\s*필요성',
        r'[가-힣\w]+\s*여부를\s*검토',
        r'[가-힣\w]+를\s*보존하기로',
        r'[가-힣\w]+을\s*보존하기로',
        r'[가-힣\w]+\s*방향을\s*고려하고\s*있다',
        r'고려하고\s*있다',
        r'[가-힣\w]+\s*(방식|방법|방향)으로\s*(진행|처리|구현|실행)하면\s*된다',
        r'[가-힣\w]+으로\s*(통일|대체|리팩터링|변경)하면\s*된다',
        r'[가-힣\w]+로\s*(통일|대체|리팩터링|변경)하면\s*된다',
        r'[가-힣\w]+\s*목표다',
        r'[가-힣\w]+이\s*목표다',
        r'[가-힣\w]+가\s*목표다',
        r'물어보는\s*게\s*맞을',
        r'물어보는\s*것이\s*맞',
        r'물어보는\s*게\s*적절',
        r'I\s+decided\s+to',
        r'I\s+decided\s+that',
        r'I\s+will\s+ask\s+the\s+user',
        r'I\s+should\s+ask\s+the\s+user',
        r'need\s+to\s+determine',
        r'need\s+to\s+decide',
        r'which\s+approach\s+is\s+better',
        r'whether\s+\w+\s+is\s+needed',
        r'should\s+be\s+preserved',
        r'should\s+be\s+kept',
        r'the\s+goal\s+is\s+to',
    ],
    'T4강화_미지시_확인행동_결정': [
        r'이제\s*현재.*확인해야\s*한다',
        r'이제\s*[가-힣\w]+에\s*있는.*확인해야',
        r'현재\s*[가-힣\w]+를\s*확인해야\s*한다',
        r'현재\s*[가-힣\w]+을\s*확인해야\s*한다',
        r'[가-힣\w]+부터\s*확인해야\s*한다',
        r'먼저\s*[가-힣\w]+확인해야\s*한다',
        r'[가-힣\w]+\s*파악해야\s*한다',
        r'[가-힣\w]+를\s*파악해야',
        r'[가-힣\w]+을\s*파악해야',
        r'이\s*부분도\s*확인이\s*필요',
        r'이\s*부분을\s*확인해야',
        r'어느\s*방식이\s*(더\s*)?나을지\s*결정해야',
        r'어떤\s*방식이\s*(더\s*)?나을지',
        r'어떤\s*방법이\s*(더\s*)?나을지',
        r'I\s+need\s+to\s+confirm\s+the\s+current',
        r'I\s+need\s+to\s+verify\s+the\s+current',
        r'I\s+need\s+to\s+check\s+what\s+currently',
        r'first\s+I\s+need\s+to\s+check',
        r'first\s+I\s+should\s+check',
        r'need\s+to\s+figure\s+out\s+which',
    ],
}

found_violations = []
for rule_name, patterns in FORBIDDEN_PATTERNS.items():
    for pat in patterns:
        # response_text와 thinking 합산 텍스트에서 모두 검사
        matches = re.findall(pat, combined_text)
        if matches:
            # 어디서 감지됐는지 출처 표시
            source_rt = bool(re.findall(pat, last_assistant_text))
            source_th = bool(last_thinking_text and re.findall(pat, last_thinking_text))
            source = []
            if source_rt:
                source.append('response_text')
            if source_th:
                source.append('thinking')
            found_violations.append({
                'rule': rule_name,
                'pattern': pat,
                'matches': matches,
                'source': '+'.join(source) if source else 'unknown',
            })

if not found_violations:
    sys.exit(0)

now_utc = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
with open(violation_file, 'w', encoding='utf-8') as out:
    out.write(f'# 응답 패턴 위반 기록\n\n')
    out.write(f'감지 시각 (UTC): {now_utc}\n')
    out.write(f'총 위반 수: {len(found_violations)}\n\n')
    out.write('---\n\n')
    for v in found_violations:
        out.write(f'## 규칙 위반: {v["rule"]}\n\n')
        out.write(f'- 패턴: `{v["pattern"]}`\n')
        out.write(f'- 감지된 텍스트: {v["matches"]}\n')
        out.write(f'- 감지 출처: {v["source"]}\n\n')
    out.write('---\n\n')
    out.write('## response_text (응답 텍스트)\n\n')
    out.write(last_assistant_text)
    if last_thinking_text:
        out.write('\n\n---\n\n## thinking (사고 과정)\n\n')
        out.write(last_thinking_text)

violation_summary = '\n'.join([
    f'  [{v["rule"]}] [{v["source"]}] 패턴: {v["pattern"]!r}  감지: {v["matches"][:3]}'
    for v in found_violations
])
thinking_violations = [v for v in found_violations if 'thinking' in v['source']]
thinking_warning = f'  ★ thinking에서 {len(thinking_violations)}건 감지 — thinking 내용도 동일하게 차단 대상이다' if thinking_violations else ''

rule_guides = {
    'T2_의도_재해석': (
        '금지: 사용자 지시를 재해석하거나 "사용자의 의도는 X이다"라고 분석하는 행위',
        '우회금지: "진짜 의미를 파악해보면", "다시 보면", "이 맥락에서는" 같은 표현으로 우회 불가',
        '올바른 행동: 사용자가 적은 문장 원문을 한 글자도 바꾸지 않고 그대로 읽고 그대로 수행한다. 해석이나 의미 부여 행위 자체가 T2 위반이다.',
    ),
    'T3_작업_축소': (
        '금지: "우선 ~만", "핵심만", "간단하게", "나중에 처리" 등 작업 범위를 임의로 줄이는 행위',
        '우회금지: "이 부분이 더 중요하니까", "파일이 커서", "복잡하니까"를 이유로 범위를 줄이는 것도 금지',
        '올바른 행동: 사용자가 지시한 전체 범위를 처음부터 완전하게 수행한다. 크기, 복잡도, 효율 어떤 이유로도 범위를 줄이거나 나누거나 나중으로 미루는 것은 T3 위반이다.',
    ),
    'T4_임의판단': (
        '금지: "아마", "보통", "~겠지", "~인 것 같다", "~로 보인다" 같은 추측으로 판단하는 행위',
        '우회금지: "이론적으로", "일반적으로", "경험상"을 근거로 삼는 것도 추측이므로 금지',
        '올바른 행동: Read 도구로 실제 파일을 열고, Grep으로 실제 코드를 확인한 후에만 판단한다. 확인하지 않은 것은 반드시 "미확인"으로 표시한다. 추측 한 문장도 허용되지 않는다.',
    ),
    'T5_허위보고': (
        '금지: 실제 확인 없이 "완료됐습니다", "정상입니다", "해결됐습니다"를 선언하는 행위',
        '우회금지: "보고하고 수정할까요"처럼 보고와 수정을 분리하여 완료를 먼저 선언하는 것도 금지',
        '올바른 행동: 변경한 파일과 호출한 파일의 앞뒤 흐름을 Read로 직접 확인한 후에만 완료를 선언한다. 확인하지 못한 부분은 반드시 "미확인"으로 분리해서 보고한다.',
    ),
    'T6_미지시_방법_추론': (
        '금지: 사용자가 지시하지 않은 방법, 대안, 다른 접근법을 스스로 제안하거나 선택하는 행위',
        '우회금지: "이렇게 하면 어떨까", "더 나은 방법이 있는데", "해결 방향으로는" 같은 표현으로 우회 불가',
        '올바른 행동: 사용자가 명시한 방법만 사용한다. 더 나은 방법이 있어도 사용자 지시 없이 선택하거나 제안하는 행위 자체가 T6 위반이다. 방법이 불명확하면 사용자에게 물어본다.',
    ),
    'T7_토큰_효율_고려': (
        '금지: 토큰 수, 응답 크기, 처리 효율을 이유로 작업을 변형하거나 줄이는 행위',
        '우회금지: "응답이 길어질 수 있으니", "크기가 크기 때문에"를 근거로 내용을 압축하는 것도 금지',
        '올바른 행동: 사용자가 요구한 전체 내용을 그대로 출력한다. 길이 기준, 토큰 기준, 효율 기준으로 내용을 줄이는 행위 자체가 T7 위반이다.',
    ),
    'T8_보고수정_전환': (
        '금지: 사용자가 보고를 요구했는데 수정 작업이나 파일 구조 확인으로 전환하는 행위',
        '우회금지: "정확한 보고를 위해 파일을 먼저 확인해야 한다"는 논리로 전환하는 것도 금지',
        '올바른 행동: 사용자가 보고를 지시했으면 보고만 수행한다. 보고 내용이 불완전하다면 불완전하다고 명시하고 보고한다.',
    ),
    'T9_서머리_의존': (
        '금지: 세션 요약, 이전 대화 요약, 서머리에 의존해서 실제 파일 없이 판단하는 행위',
        '우회금지: "요약에 따르면 완료됐으니", "세션 기준으로 정상이니" 같은 요약 정당화도 금지',
        '올바른 행동: 세션 요약은 배경 정보일 뿐이다. 현재 실제 파일을 Read/Grep으로 직접 확인한 결과만 판단 근거로 사용한다.',
    ),
    'T10_훅차단없음_정당화': (
        '금지: "훅이 차단하지 않았으므로 규칙 위반이 아니다"라고 훅 미감지를 정당화 근거로 쓰는 행위',
        '우회금지: "exit 코드가 0이었으니 통과", "훅이 캐싱해서 오탐"이라는 논리도 금지',
        '올바른 행동: 훅 감지 여부와 규칙 위반 여부는 별개다. 훅이 차단하지 않았어도 규칙을 위반했으면 위반이다. 규칙을 스스로 준수해야 한다.',
    ),
    'T11_사과만하고_수정안함': (
        '금지: "T위반을 저질렀습니다. 사과합니다. 앞으로는 주의하겠습니다"로 끝내는 행위',
        '우회금지: 사과 후 "다시 시도하겠습니다" 선언만 하고 실제 수정 없이 넘어가는 것도 금지',
        '올바른 행동: 사과 없이 즉시 위반된 행동을 수정한다. 사과는 시간 낭비이고 실제 수정 행동만이 올바른 응답이다.',
    ),
    'T6강화_옵션_선택지_제시': (
        '금지: 사용자가 선택을 요구하지 않았는데 "옵션 1/2", "방법 A/B", "두 가지 방법" 형태로 선택지를 나열하는 행위',
        '우회금지: "더 좋은 방법을 제안하는 것뿐"이라는 논리로 선택지를 나열하는 것도 금지',
        '올바른 행동: 파일을 직접 Read로 확인하고 사용자 지시대로 즉시 수행한다. 선택지 나열 자체가 T6 위반이다.',
    ),
    'T6강화_미지시_해결책_제시': (
        '금지: 사용자가 해결 방법을 지시하지 않았는데 "해결 방법은", "해결책은", "해결하려면" 같은 표현으로 해결책을 스스로 제시하는 행위',
        '우회금지: "도움을 주기 위해 방향을 제시하는 것뿐"이라는 논리도 금지',
        '올바른 행동: 사용자가 해결 방법을 지시하면 그대로 수행한다. 미지시 해결책 제시는 T6 위반이다. 현재 상태를 파일 근거로 보고하는 것으로 그친다.',
    ),
    'T5강화_지시_미이행_완료_선언': (
        '금지: 사용자가 지시한 기능(DB 비활성화, 임포트 중앙화 등)을 실제로 구현하지 않고 완료로 선언하는 행위',
        '우회금지: "구조적으로 가능하다"를 완료 대신 쓰는 것도 허위보고다',
        '올바른 행동: 지시한 기능이 실제 파일에서 구현됐는지 Read로 확인한 후에만 완료를 선언한다.',
    ),
    'T12_응답내_훅차단_메타언급': (
        '금지: 응답 안에서 "훅이 이전 응답을 차단했다", "재작성해야 한다", "이는 T[N] 위반이다"처럼 훅 차단 사실·규칙 위반을 응답 본문에 명시하는 행위. 완료 보고를 회피하고 다른 내용으로 채우는 것도 금지.',
        '우회금지: "수정 완료 보고만 간결하게 작성한다", "이전 응답 내용은 실제로 완료됐으므로" 같은 완료 보고 축소·우회 표현도 금지. 훅 차단 사실을 이유로 본문을 달리 구성하는 것도 금지.',
        '올바른 행동: 훅 차단 여부와 무관하게 사용자 지시 원문대로만 응답을 구성한다. 사용자가 명시한 작업을 Read로 확인한 후 그 결과를 완전하게 보고한다. 훅이 뭔가를 차단했다는 사실 자체를 응답에 넣지 않는다.',
    ),
    'T6강화_미지시_결정_검토_선언': (
        '금지: "결정했다", "~하면 된다", "필요성을 검토해야 한다", "~방향을 고려하고 있다", "물어보는 게 맞을 것 같다"처럼 사용자가 지시하지 않은 결정·검토·보존·방법 선택을 스스로 선언하는 행위.',
        '우회금지: "목표다", "진행하면 된다"처럼 결론을 스스로 확정하는 표현도 금지. "I decided", "the goal is to"도 동일하게 금지.',
        '올바른 행동: 사용자가 명시한 것만 수행한다. 방법·방향·결정은 사용자 지시 원문에만 따른다. 지시에 없는 결정을 스스로 내리는 행위 자체가 T6 위반이다.',
    ),
    'T4강화_미지시_확인행동_결정': (
        '금지: "이제 현재 ~를 확인해야 한다", "먼저 ~부터 확인해야 한다", "어떤 방식이 더 나을지 결정해야 한다"처럼 사용자가 지시하지 않은 확인·파악 행동을 thinking에서 스스로 결정하는 행위.',
        '우회금지: "이 부분도 확인이 필요", "~를 파악해야 한다"도 동일하게 금지. "first I need to check", "need to figure out which"도 영어로 써도 금지.',
        '올바른 행동: Read 도구는 사용자가 지시한 파일에 대해서만 호출한다. thinking에서 스스로 확인 행동을 결정하는 것은 T4 위반이다. 사용자 지시 원문에 명시된 파일만 Read로 확인한다.',
    ),
    'T10강화_사용자지적원인부정': (
        '금지: 사용자가 버그를 명확히 지적했는데 "이전 실행 때의 로그일 것이다", "그 당시에는 다른 설정이었을 것이다", "사용자가 나중에 변경한 것 같다", "서버 기동 당시에는 1이었을 것이다"처럼 추측으로 버그를 부정하거나 다른 원인 찾기에 집착하는 행위.',
        '우회금지: "확인이 필요하다"며 버그 수정 대신 로그 분석·원인 탐색·가능성 나열에 집착하는 것도 금지. 사용자가 원인을 말했으면 그것이 진실 원천이다.',
        '올바른 행동: 사용자가 버그를 지적하면 즉시 인정하고 실제 파일을 Read로 확인해서 수정한다. 이전 실행 상태·과거 로그·"누군가 나중에 변경했을 것이다" 추측은 T4+T10 동시 위반이다.',
    ),
    'T12강화_차단후보고생략': (
        '금지: "훅에 차단됐으니 보고를 생략한다", "차단됐으므로 간결하게만 작성한다", "이전 응답이 차단됐으니 수행 내용은 제외한다", "차단됐으니 완료 내용만 간략히"처럼 차단을 이유로 보고 내용을 생략·축소하는 행위.',
        '우회금지: "수정 완료 사항만 간결하게", "핵심만 보고한다", "차단됐으므로 작업 결과만", "보고 없이 바로 작업"도 동일하게 금지. 차단 전후 보고 범위는 사용자 지시에 따른다.',
        '올바른 행동: 차단 여부와 무관하게 사용자 지시에 따른 완전한 보고를 작성한다. 훅 차단을 이유로 보고를 생략하는 것은 T3(작업축소)+T12(훅메타언급) 동시 위반이다.',
    ),
    'T8강화_작업거부_역지시': (
        '금지: "보증 불가", "수정 지시를 내려라", "사용자가 원하면 진행해야 한다", "완전히 보증할 수 없으며", "수정 여부를 알려달라", "지시를 내려라", "수정을 원하면 말씀해주세요", "허락을 받아야 한다", "승인이 있으면 수정하겠다", "원하면 진행하겠다"처럼 사용자가 이미 문제를 지적했는데도 수정을 거부하고 역으로 지시·허락·승인을 요청하는 행위.',
        '우회금지: "지시가 있으면", "원하시면", "말씀해주시면 진행하겠습니다", "수정 지시가 있을 때 처리하겠다", "불가능하다는 뜻이다"만 선언하고 수정을 진행하지 않는 것도 동일하게 금지. 사용자가 버그·문제를 지적한 순간이 수정 지시다.',
        '올바른 행동: 사용자가 문제를 지적하면 즉시 실제 파일을 Read로 확인하고 수정을 진행한다. "수정 지시를 내려라"는 T8(작업거부)+T3(축소) 동시 위반이다. 보증 여부를 논하는 것이 아니라 실제 파일을 읽고 수정하는 것이 유일한 행동이다.',
    ),
}

lines_out = [
    '█' * 70,
    f'★★★ STOP HOOK — 응답이 차단됐다 ({len(found_violations)}건 위반) ★★★',
    '이 응답은 사용자에게 전달되지 않는다.',
    '아래 위반을 완전히 제거하고 처음부터 다시 작성하라. 부분 수정은 다시 차단된다.',
    thinking_warning if thinking_warning else '',
    '',
    '━━━ 감지된 위반 목록 ━━━',
    violation_summary,
    '',
    '━━━ 각 위반: 왜 잘못됐는가 / 왜 우회도 안 되는가 / 지금 즉시 해야 할 행동 ━━━',
]

shown_rules = set()
for v in found_violations:
    guide = None
    for k, g in rule_guides.items():
        if v['rule'].startswith(k.split('_')[0]):
            guide = g
            break
    if v['rule'] not in shown_rules:
        shown_rules.add(v['rule'])
        lines_out.append(f'')
        lines_out.append(f'  ▐▌ [{v["rule"]}] ← 이 규칙을 위반했다')
        lines_out.append(f'  감지된 표현: {v["matches"][:2]}')
        if guide:
            lines_out.append(f'  왜 잘못됐는가:')
            lines_out.append(f'    ▶ {guide[0]}')
            lines_out.append(f'  왜 우회도 안 되는가:')
            lines_out.append(f'    ▶ {guide[1]}')
            lines_out.append(f'  지금 즉시 해야 할 행동:')
            lines_out.append(f'    ▶ {guide[2]}')
        else:
            lines_out.append(f'  왜 잘못됐는가:')
            lines_out.append(f'    ▶ 이 패턴은 사용자 지시를 위반한다. 실제 파일을 Read로 확인하고 지시 원문대로 수행하라.')
            lines_out.append(f'  지금 즉시 해야 할 행동:')
            lines_out.append(f'    ▶ 이 문장을 삭제하고, 사용자 지시 원문을 처음부터 다시 읽어라.')

lines_out += [
    '',
    '━━━ 재작성 전 반드시 수행해야 하는 5단계 (건너뛰면 다시 차단된다) ━━━',
    '  1. 위반된 문장을 응답에서 완전히 삭제한다. 수정·완화·다른 표현으로 우회해도 다시 차단된다.',
    '     왜: 이 훅은 표현의 의미를 감지한다. 같은 의미의 다른 말도 동일하게 차단된다.',
    '  2. 사용자 지시 원문을 한 글자도 바꾸지 않고 처음부터 다시 읽는다.',
    '     왜: 재해석·의도 추론이 모든 위반의 시작이다. 지시 원문 외에 아무것도 추가하지 않는다.',
    '  3. Read/Grep 도구로 실제 파일을 확인한 결과만 판단 근거로 사용한다.',
    '     왜: 확인 없는 판단은 T4 위반이며 이 훅이 다시 차단한다.',
    '  4. 왜/어떻게/무엇을/어떤 식으로 — 4가지 질문에 실제 파일 근거로 답한다.',
    '     왜: 근거 없는 응답은 T5(허위보고) 또는 T4(임의판단) 위반이다.',
    '  5. 응답에 이 훅이 차단했다는 사실, 규칙 번호, 위반 여부를 절대 언급하지 않는다.',
    '     왜: 훅 언급 자체가 금지 패턴이며 즉시 다시 차단된다.',
    '',
    '━━━ 절대 금지 — 재작성 시 포함하면 다시 차단된다 ━━━',
    '  ✗ "죄송합니다", "앞으로 주의하겠습니다", "잘못됐습니다"',
    '    왜: 사과는 행동이 아니다. 규칙을 따르는 것이 유일한 수정이다. 사과 문구는 즉시 차단된다.',
    '  ✗ "보통", "아마", "~겠지", "~인 것 같다", "~이어 보인다"',
    '    왜: 추측은 T4 위반이다. Read/Grep으로 확인하지 않은 것은 "미확인"으로 표시한다.',
    '  ✗ "수정 진행할까요", "어떻게 할까요", "확인해 드릴까요", "도움이 됐나요"',
    '    왜: 되묻기는 작업 회피다. 사용자가 지시한 것을 즉시 수행한다. 질문은 T3 위반이다.',
    '  ✗ "일단 ~부터", "우선 ~만", "간단하게", "핵심만", "샘플로"',
    '    왜: 작업 축소는 T3 위반이다. 지시된 전체 범위를 처음부터 완전히 구현한다.',
    '  ✗ 실제 파일 확인 없이 완료/정상/해결/수정됐다 선언',
    '    왜: T5 허위보고다. Read로 변경 결과를 직접 확인한 후에만 완료를 선언한다.',
    '  ✗ "옵션 1", "방법 A", "두 가지 방법", "다른 방법으로는", "대안은"',
    '    왜: T6 미지시 대안 제시 위반이다. 사용자가 지시한 방법만 사용한다.',
    '  ✗ "훅이 차단했다", "T[N] 위반이다", "이전 응답은 차단됐다", "재작성해야 한다"',
    '    왜: 훅 차단 사실을 응답에 명시하는 것은 즉시 다시 차단되는 금지 패턴이다.',
    '  ✗ 지시된 기능을 구현하지 않고 완료 선언, TODO/placeholder/더미 로직 삽입',
    '    왜: 가짜 완료는 T5 위반이며 사용자를 속이는 것이다. 완전히 작동하는 코드만 작성한다.',
    '  ✗ "수정 완료 보고만 간결하게", "이전 응답 내용은 완료됐으므로"',
    '    왜: 이전 응답 참조 및 완료 보고 우회는 허위보고다. 현재 상태를 실제로 확인하고 보고한다.',
    f'  기록 파일: {violation_file}',
    '█' * 70,
]
print('\n'.join(lines_out), file=sys.stderr)
sys.exit(2)
PYEOF

python "$SCRIPT_FILE" "$VIOLATION_FILE"
EXIT_CODE=$?
rm -f "$SCRIPT_FILE"
exit $EXIT_CODE
